import catalunyaDetail from "@/assets/catalunya_detail_track.png";
import austriaDetail from "@/assets/austria_detail_track.png";
import silverstoneDetail from "@/assets/silverstone_detail_track.png";
import spaDetail from "@/assets/spa_detail_track.png";

export type Driver = { name: string; team: string };
export type PodiumEntry = Driver & { time?: string };
export type QualiEntry = Driver & { time?: string };

export type GrandPrixHistory = {
  officialName: string;
  firstHeld: number;
  trackLength: string;
  laps: number;
  lapRecord: { driver: string; time: string; year: number };
  mostWins: { driver: string; count: number };
  summary: string;
  detailMapImage?: string;
  lastYear: {
    season: number;
    race: PodiumEntry[];
    quali: QualiEntry[];
  };
};

export const GP_HISTORY: Record<string, GrandPrixHistory> = {
  spa: {
    officialName: 'FORMULA 1 BELGIAN GRAND PRIX 2026',
    firstHeld: 1950,
    trackLength: '7.004 km',
    laps: 44,
    lapRecord: { driver: 'Sergio Pérez', time: '1:44.701', year: 2024 },
    mostWins: { driver: 'Michael Schumacher', count: 6 },
    summary:
      'Spa-Francorchamps is the longest lap on the Formula 1 calendar and one of its most dramatic: a roller-coaster through the Ardennes forests with big elevation changes, blind crests and the legendary Eau Rouge–Raidillon climb. First raced as a championship Grand Prix in 1950, it rewards bravery through Pouhon and Blanchimont and often throws wet weather into the mix. A win at the Belgian Grand Prix is one of the most celebrated trophies of the season.',
    detailMapImage: spaDetail,
    lastYear: {
      season: 2025,
      race: [
        { name: 'Oscar Piastri', team: 'McLaren', time: '1:25:22.601' },
        { name: 'Lando Norris', team: 'McLaren', time: '+3.415' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '+20.185' },
        { name: 'Max Verstappen', team: 'Red Bull', time: '+21.731' },
        { name: 'George Russell', team: 'Mercedes', time: '+34.863' },
        { name: 'Alexander Albon', team: 'Williams', time: '+39.926' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '+40.679' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: '+52.033' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: '+56.434' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '+1:12.714' },
        { name: 'Oliver Bearman', team: 'Haas', time: '+1:13.145' },
        { name: 'Nico Hülkenberg', team: 'Kick Sauber', time: '+1:13.628' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '+1:15.395' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: '+1:19.831' },
        { name: 'Esteban Ocon', team: 'Haas', time: '+1:26.063' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: '+1:26.721' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '+1:27.924' },
        { name: 'Carlos Sainz', team: 'Williams', time: '+1:32.024' },
        { name: 'Franco Colapinto', team: 'Alpine', time: '+1:35.250' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: '+1 lap' },
      ],
      quali: [
        { name: 'Lando Norris', team: 'McLaren', time: '1:40.562' },
        { name: 'Oscar Piastri', team: 'McLaren', time: '1:40.647' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '1:40.900' },
        { name: 'Max Verstappen', team: 'Red Bull', time: '1:40.903' },
        { name: 'Alexander Albon', team: 'Williams', time: '1:41.201' },
        { name: 'George Russell', team: 'Mercedes', time: '1:41.260' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '1:41.284' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: '1:41.310' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: '1:41.328' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: '1:42.387' },
        { name: 'Esteban Ocon', team: 'Haas', time: '1:41.525' },
        { name: 'Oliver Bearman', team: 'Haas', time: '1:41.617' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '1:41.633' },
        { name: 'Nico Hülkenberg', team: 'Kick Sauber', time: '1:41.707' },
        { name: 'Carlos Sainz', team: 'Williams', time: '1:41.758' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '1:41.939' },
        { name: 'Franco Colapinto', team: 'Alpine', time: '1:42.022' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: '1:42.139' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '1:42.385' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: '1:42.502' },
      ],
    },
  },
  silverstone: {
    officialName: 'FORMULA 1 BRITISH GRAND PRIX 2026',
    firstHeld: 1950,
    trackLength: '5.891 km',
    laps: 52,
    lapRecord: { driver: 'Max Verstappen', time: '1:27.097', year: 2020 },
    mostWins: { driver: 'Lewis Hamilton', count: 9 },
    summary:
      'Silverstone is the birthplace of the Formula 1 World Championship — it hosted the very first round of the inaugural 1950 season on the runways of a former World War II RAF bomber airfield. It remains one of the fastest and most physical laps of the year: the flat-out sweep of Copse, the daunting Maggotts–Becketts–Chapel complex and the long Hangar Straight into Stowe all reward commitment and a car that stays planted through high-speed direction changes. Backed by a huge and passionate home crowd, a win at the British Grand Prix is one of the most prized on the calendar.',
    detailMapImage: silverstoneDetail,
    lastYear: {
      season: 2025,
      race: [
        { name: 'Lando Norris', team: 'McLaren', time: '1:37:15.735' },
        { name: 'Oscar Piastri', team: 'McLaren', time: '+6.812' },
        { name: 'Nico Hülkenberg', team: 'Kick Sauber', time: '+34.742' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '+39.812' },
        { name: 'Max Verstappen', team: 'Red Bull', time: '+56.781' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '+59.857' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: '+1:00.603' },
        { name: 'Alexander Albon', team: 'Williams', time: '+1:04.135' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '+1:05.858' },
        { name: 'George Russell', team: 'Mercedes', time: '+1:10.674' },
        { name: 'Oliver Bearman', team: 'Haas', time: '+1:12.095' },
        { name: 'Carlos Sainz', team: 'Williams', time: '+1:16.592' },
        { name: 'Esteban Ocon', team: 'Haas', time: '+1:17.301' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '+1:24.477' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '+1 lap' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: 'DNF' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: 'DNF' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: 'DNF' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: 'DNF' },
        { name: 'Franco Colapinto', team: 'Alpine', time: 'DNS' },
      ],
      quali: [
        { name: 'Max Verstappen', team: 'Red Bull', time: '1:24.892' },
        { name: 'Oscar Piastri', team: 'McLaren', time: '1:24.995' },
        { name: 'Lando Norris', team: 'McLaren', time: '1:25.010' },
        { name: 'George Russell', team: 'Mercedes', time: '1:25.029' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '1:25.095' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '1:25.121' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: '1:25.374' },
        { name: 'Oliver Bearman', team: 'Haas', time: '1:25.471' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '1:25.621' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '1:25.785' },
        { name: 'Carlos Sainz', team: 'Williams', time: '1:25.746' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '1:25.826' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: '1:25.864' },
        { name: 'Alexander Albon', team: 'Williams', time: '1:25.889' },
        { name: 'Esteban Ocon', team: 'Haas', time: '1:25.950' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: '1:26.440' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: '1:26.446' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: '1:26.504' },
        { name: 'Nico Hülkenberg', team: 'Kick Sauber', time: '1:26.574' },
        { name: 'Franco Colapinto', team: 'Alpine', time: '1:27.060' },
      ],
    },
  },
  austria: {
    officialName: 'GROSSER PREIS VON ÖSTERREICH 2026',
    firstHeld: 1970,
    trackLength: '4.318 km',
    laps: 70,
    lapRecord: { driver: 'Carlos Sainz', time: '1:05.619', year: 2020 },
    mostWins: { driver: 'Max Verstappen', count: 4 },
    summary:
      'The Red Bull Ring sits high in the Styrian mountains above Spielberg and is the shortest lap on the calendar by time — a flying lap is barely over a minute. There are only ten corners, but big elevation changes and three heavy uphill braking zones make it one of the best overtaking tracks of the year. First raced in 1970 as the Österreichring and reborn as the Red Bull-owned Red Bull Ring in 2011, it rewards traction out of the slow corners, braking stability and bravery over the blind crests.',
    detailMapImage: austriaDetail,
    lastYear: {
      season: 2025,
      race: [
        { name: 'Lando Norris', team: 'McLaren', time: '1:23:47.693' },
        { name: 'Oscar Piastri', team: 'McLaren', time: '+2.695' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '+19.820' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '+29.020' },
        { name: 'George Russell', team: 'Mercedes', time: '+1:02.396' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: '+1:07.754' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '+1 lap' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: '+1 lap' },
        { name: 'Nico Hulkenberg', team: 'Kick Sauber', time: '+1 lap' },
        { name: 'Esteban Ocon', team: 'Haas', time: '+1 lap' },
        { name: 'Oliver Bearman', team: 'Haas', time: '+1 lap' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: '+1 lap' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '+1 lap' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: '+1 lap' },
        { name: 'Franco Colapinto', team: 'Alpine', time: '+1 lap' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '+2 laps' },
        { name: 'Alexander Albon', team: 'Williams', time: 'DNF' },
        { name: 'Max Verstappen', team: 'Red Bull', time: 'DNF' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: 'DNF' },
        { name: 'Carlos Sainz', team: 'Williams', time: 'DNS' },
      ],
      quali: [
        { name: 'Lando Norris', team: 'McLaren', time: '1:03.971' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '1:04.492' },
        { name: 'Oscar Piastri', team: 'McLaren', time: '1:04.554' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '1:04.582' },
        { name: 'George Russell', team: 'Mercedes', time: '1:04.763' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: '1:04.926' },
        { name: 'Max Verstappen', team: 'Red Bull', time: '1:04.929' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: '1:05.132' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: '1:05.276' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '1:05.649' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '1:05.128' },
        { name: 'Alexander Albon', team: 'Williams', time: '1:05.205' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: '1:05.226' },
        { name: 'Franco Colapinto', team: 'Alpine', time: '1:05.288' },
        { name: 'Oliver Bearman', team: 'Haas', time: '1:05.312' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: '1:05.329' },
        { name: 'Esteban Ocon', team: 'Haas', time: '1:05.364' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '1:05.369' },
        { name: 'Carlos Sainz', team: 'Williams', time: '1:05.582' },
        { name: 'Nico Hulkenberg', team: 'Kick Sauber', time: '1:05.606' },
      ],
    },
  },
  barcelona: {
    officialName: 'GRAN PREMIO DE BARCELONA-CATALUNYA 2026',
    firstHeld: 1991,
    trackLength: '4.657 km',
    laps: 66,
    lapRecord: { driver: 'Max Verstappen', time: '1:16.330', year: 2023 },
    mostWins: { driver: 'Schumacher & Hamilton', count: 6 },
    summary:
      'The Circuit de Barcelona-Catalunya has hosted the Spanish Grand Prix since 1991 and is one of the most familiar tracks on the calendar — most teams test here every winter. Located in Montmeló, just north of Barcelona, it mixes high-speed sweepers, long straights and a now faster, more flowing final sector (following the removal of the chicane ahead of the 2023 season). The result is a complete test of aero balance and tyre management; overtaking is famously hard, so qualifying counts double.',
    detailMapImage: catalunyaDetail,
    lastYear: {
      season: 2025,
      race: [
        { name: 'Oscar Piastri', team: 'McLaren', time: '1:32:57.375' },
        { name: 'Lando Norris', team: 'McLaren', time: '+2.471' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '+10.455' },
        { name: 'George Russell', team: 'Mercedes', time: '+11.359' },
        { name: 'Nico Hulkenberg', team: 'Kick Sauber', time: '+13.648' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '+15.508' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: '+16.022' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '+17.882' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '+21.564' },
        { name: 'Max Verstappen', team: 'Red Bull', time: '+21.826' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: '+25.532' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: '+25.996' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '+28.822' },
        { name: 'Carlos Sainz', team: 'Williams', time: '+29.309' },
        { name: 'Franco Colapinto', team: 'Alpine', time: '+31.381' },
        { name: 'Esteban Ocon', team: 'Haas', time: '+32.197' },
        { name: 'Oliver Bearman', team: 'Haas', time: '+37.065' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: 'DNF' },
        { name: 'Alexander Albon', team: 'Williams', time: 'DNF' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: 'DNS' },
      ],
      quali: [
        { name: 'Oscar Piastri', team: 'McLaren', time: '1:11.546' },
        { name: 'Lando Norris', team: 'McLaren', time: '1:11.755' },
        { name: 'Max Verstappen', team: 'Red Bull', time: '1:11.848' },
        { name: 'George Russell', team: 'Mercedes', time: '1:11.848' },
        { name: 'Lewis Hamilton', team: 'Ferrari', time: '1:12.045' },
        { name: 'Kimi Antonelli', team: 'Mercedes', time: '1:12.111' },
        { name: 'Charles Leclerc', team: 'Ferrari', time: '1:12.131' },
        { name: 'Pierre Gasly', team: 'Alpine', time: '1:12.199' },
        { name: 'Isack Hadjar', team: 'Racing Bulls', time: '1:12.252' },
        { name: 'Fernando Alonso', team: 'Aston Martin', time: '1:12.284' },
        { name: 'Alexander Albon', team: 'Williams', time: '1:12.641' },
        { name: 'Gabriel Bortoleto', team: 'Kick Sauber', time: '1:12.756' },
        { name: 'Liam Lawson', team: 'Racing Bulls', time: '1:12.763' },
        { name: 'Lance Stroll', team: 'Aston Martin', time: '1:13.058' },
        { name: 'Oliver Bearman', team: 'Haas', time: '1:13.315' },
        { name: 'Nico Hulkenberg', team: 'Kick Sauber', time: '1:13.190' },
        { name: 'Esteban Ocon', team: 'Haas', time: '1:13.201' },
        { name: 'Carlos Sainz', team: 'Williams', time: '1:13.203' },
        { name: 'Franco Colapinto', team: 'Alpine', time: '1:13.334' },
        { name: 'Yuki Tsunoda', team: 'Red Bull', time: '1:13.385' },
      ],
    },
  },
};

export function getGrandPrixHistory(circuitId: string): GrandPrixHistory | null {
  return GP_HISTORY[circuitId] ?? null;
}
